[package]
name = "translator"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
ring = "0.16"
hmac = "0.12"
chrono = "0.4"
hex = "0.4"